name: build and test

on:
  push:
    branches: [ main , latest ]
  pull_request:
    branches: [ main , latest ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm i
    #- run: npm run test

