name: build and test

on:
  push:
    branches: [ main , latest ]
  pull_request:
    branches: [ main , latest ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: akrck02/gtd-lib-test:v1
    steps:
    - uses: actions/checkout@v2
      with: 
        path: "GTD-LIB-TS"
    - name: RunTest
      run: | sh scripts/docker.test.cli.sh

